# Generated by Django 5.2.7 on 2026-03-02 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_label', models.CharField(blank=True, max_length=50)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('class_incharge', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.class')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.class')),
            ],
            options={
                'ordering': ['row_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.class')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('class_ref', 'year', 'month', 'day'), name='unique_holiday_date')],
            },
        ),
        migrations.CreateModel(
            name='MonthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('num_days', models.PositiveIntegerField(default=31)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_configs', to='core.class')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('class_ref', 'month', 'year'), name='unique_class_month_year')],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.column')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.row')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('row', 'column'), name='unique_row_column')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('status', models.CharField(default='A', max_length=1)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.row')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('row', 'year', 'month', 'day'), name='unique_attendance')],
            },
        ),
    ]
